### ISSUE TITLE
mouse-look: Broken event listeners for requestPointerLock

### ISSUE THREAD

**Issue by Srile** [WonderlandEngine/components#48]
https://github.com/WonderlandEngine/components/blob/main/mouse-look.ts#L47C35-L48C10

To run `requestPointerLock` with the engine's canvas, the function needs to be bound using .bind(this) to work.

It is important to also save the bound function as a reference in the function for the removal of the listener in `onDeactivate`.

**Comment by Squareys** [comment]
It doesn't, because the `() => {}` (arrow notated function) binds the instance scope. Is it really not working for you?
